todo/urls.py
from django.urls import path
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, TaskDelete, CustomLoginView, RegisterPage,about
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', TaskList.as_view(), name="task"),
    path('task-create/', TaskCreate.as_view(), name="task-create"),
    path('login/', CustomLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page='login'), name="logout"),
    path('register/', RegisterPage.as_view(), name="register"),
    path('task/<int:pk>/', TaskDetail.as_view(), name="tasks-detail"),
    path('task-update/<int:pk>/', TaskUpdate.as_view(), name="tasks-update"),
    path('task-delete/<int:pk>/', TaskDelete.as_view(), name="tasks-delete"),
    path('about/',about,name='about'),
]

todolistprj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls'))
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200, null=True)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['complete']

todo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.views import LoginView
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Task
def about(request):
    return render(request, 'todo/about.html')
class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'task'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task'] = context['task'].filter(user=self.request.user)
        context['count'] = context['task'].filter(complete=False).count()

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['task'] = context['task'].filter(title__icontains = search_input)
            context['search_input'] = search_input
        return context

class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'todo/task.html'


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['title', 'description', 'complete']
    # fields = ['title', 'description']
    success_url = reverse_lazy('task')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)

class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('task')


class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('task')


class CustomLoginView(LoginView):
    template_name = 'todo/login.html'
    fields = "__all__"
    redirect_authenticated_user = False

    def get_success_url(self):
        return reverse_lazy('task')
class RegisterPage(FormView):
    template_name = 'todo/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('task')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('task')
        return super(RegisterPage, self).get(*args, *kwargs)

todo/templates/todo/about.html
<!DOCTYPE html>

<html lang="en" data-bs-theme="auto">
{% load static %}
  <head>
<meta charset="UTF-8">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
    <title>About Us</title>
 {% include 'todo/design.html' %}
  </head>
  <body>
<header data-bs-theme="dark">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
  <div class="container-fluid">
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="">About Us</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</header>


<main class="py-5 text-center">
<p class="fw-normal" >This web application helps users manage their tasks and help them stay organized. The website was developed by the following software engineering international students of Nankai university:</p>
  <div class="album py-5">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'njie.jpg' %}">
            <div class="card-body">
              <p class="card-text">Isatou K. Njie</p>

              <p class="card-text"> 2120226054</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="mailto:isatoukn696@gmail.com" class=" text-reset"><i class="fas fa-envelope"></i></a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="https://www.linkedin.com/in/isatou-k-njie-b34b73185" class=" text-reset" target="_blank"> <i class="fab fa-linkedin"></i></a></button>
                </div>
              </div>
            </div>
          </div>
        </div>
       <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'nazir.jpg' %}">
            <div class="card-body">
              <p class="card-text">Ilyasu Nazir Muhammad </p>
              <p class="card-text">2120226071</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                 <button type="button" class="btn btn-sm btn-outline-secondary"><a href="mailto:nazirkaoje777@gmail.com" class=" text-reset"><i class="fas fa-envelope"></i></a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="https://www.linkedin.com/in/nazir-ilyasu-26238a279" class=" text-reset" target="_blank"> <i class="fab fa-linkedin"></i></a></button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'uwais.jpg' %}">
            <div class="card-body">
              <p class="card-text">Muhammad Uwais Ahmad</p>

              <p class="card-text">2120226073</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="mailto:muhduways@yahoo.com" class=" text-reset"><i class="fas fa-envelope"></i></a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="https://www.linkedin.com/in/uwais-muhammad-388833279" class=" text-reset" target="_blank"> <i class="fab fa-linkedin"></i></a></button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'abba1.jpg' %}" height=>
            <div class="card-body">
              <p class="card-text">Abba Adamu Fanda</p>
              <p class="card-text">2120226076</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="mailto:Fanda1095@gmail.com" class=" text-reset"><i class="fas fa-envelope"></i></a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="https://www.linkedin.com/in/abba-fanda-7364b4121" class=" text-reset" target="_blank"> <i class="fab fa-linkedin"></i></a></button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'mayowa.JPG' %}">
            <div class="card-body">
              <p class="card-text">Adedara Olumayowa Olukolade</p>

              <p class="card-text">2120226068</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="mailto:adedaramayowa6@gmail.com" class=" text-reset"><i class="fas fa-envelope"></i></a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="https://www.linkedin.com/in/adedara-olumayowa-o-3712061b4/" class=" text-reset" target="_blank"> <i class="fab fa-linkedin"></i></a></button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</main>
<footer class="text-center text-lg-start bg-light text-muted">

  <!-- Copyright -->
  <div class="text-center p-2" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2023 Copyright:
    <a class="text-reset fw-bold" href="">Nankai University Software Engineering Students</a>
  </div>
  <!-- Copyright -->
</footer>
</main>


      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.1/mdb.min.js"
></script>

  </body>
</html>

</body>
</html>

todo/templates/todo/design.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
      <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.111.3">
    <meta charset="UTF-8">


<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
<!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.1/mdb.min.css"
  rel="stylesheet"
/>
    <!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.1/mdb.min.css"
  rel="stylesheet"
/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <!-- Favicons -->
<meta name="theme-color" content="#712cf9">
   <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
        .bg-img{
        background-color:#6528e0;
        }

    </style>
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

todo/templates/todo/login.html
{% extends 'todo/main.html' %}

{% block content %}
<style>
    small p{
    color:#fff;
    }
</style>
<div class="header-bar">
    <h1>Login</h1>
</div>
<div class="card-body">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="button" type="submit" value="Login Now">
    <small>        <p>Don't have an account yet? <a href="{% url 'register' %}">Register </a></p>
    </small>
    </form>
</div>
{% endblock content %}

todo/templates/todo/main.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To-do App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
      <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.111.3">
    <meta charset="UTF-8">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">


<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
<!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.1/mdb.min.css"
  rel="stylesheet"
/>
    <!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.1/mdb.min.css"
  rel="stylesheet"
/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">
<!-- MDB -->

</head>
<style>


    body{
            background: url({% static 'to-do-list-background.jpg' %}) no-repeat center center fixed;
            background-size: cover;
            font-family: 'Nunito', sans-serif;
    }
    .card-body{
    text-align:center;
    }
    .header-bar {
        display: flex;
        justify-content: space-between;
        color: #fff;
        padding: 20px;
    }
    h1,
    h2,
    h3,
    h4,
    h5,
    h6
    {
    font-family: 'Raleway', sans-serif;
}
    .task-wrapper {
            display: flex;
            align-items: center;
            justify-content: space-between;
            background-color: #fff;
            border-top: 1px solid #dfe4ea;
            overflow: hidden;
        }
        .task-title {
            display: flex;
            padding: 20px;
        }

        .task-title a {
            text-decoration: none;
            color: #4b5156;
            margin-left: 10px;
        }

        .task-complete-icon {
            height: 20px;
            width: 20px;
            background-color: rgb(0, 255, 0);
            border-radius: 50%;
        }

        .task-incomplete-icon {
            height: 20px;
            width: 20px;
            background-color: rgb(160, 160, 160);
            border-radius: 50%;
        }

        .delete-link {
            text-decoration: none;
            font-weight: 900;
            color: #6249cf;
            font-size: 22px;
            line-height: 0;
            padding: 20px 20px;
        }
        .header-bar a {
            color: rgb(247, 247, 247);
            text-decoration: none;
        }
        #search-add-wrapper {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 20px;
        }
        input[type=text],
        input[type=password],
        textarea {
            border: 1px solid #757575;
            border-radius: 5px;
            padding: 10px;
            width: 50%;
            outline:0;
        }
        li{
        color:#fff;}

        label {
            padding-top: 10px !important;
            display: block;
            color:#fff;
        }

        ::placeholder {
            font-weight: 300;
            opacity: 0.5;
        }

        .button {
            border: 1px solid #757575;
            background-color: #FFF;
            color: #6249cf;
            padding: 10px;
            font-size: 14px;
            border-radius: 5px;
            cursor: pointer;
            margin-bottom:30px
        }
        #add-link {
            color: #6249cf;
            text-decoration: none;
            font-size: 42px;
            text-shadow: 1px 1px #81413b;
        }
        .card-body {
            padding: 20px;


        }
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }


</style>
<body>
<header data-bs-theme="dark">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
  <div class="container-fluid">
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About Us</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</header>
{% block content %}

        {% endblock content %}


<footer class="text-center text-lg-start bg-light text-muted fixed-bottom">


  <!-- Copyright -->
<div class="text-center p-2" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2023 Copyright:
    <a class="text-reset fw-bold" href="">Nankai University Software Engineering Students</a>
  </div>
  <!-- Copyright -->
</footer>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.1/mdb.min.js"
></script>
</body>
</html>

todo/templates/todo/register.html
{% extends 'todo/main.html' %}

{% block content %}
<style>
   small p{
   color:#fff;
   }
   .cond{
   font-size:10px;
   color:#eb344f;
   margin-bottom:0px;
   }


</style>
<div class="header-bar">
    <h1>Register</h1>
</div>

<div class="card-body">
    <form action="" method="post">
        {% csrf_token %}
        <label >{{ form.username.label }}</label>
        {{ form.username }}
    <p class="cond">Required. 150 characters or fewer. Letters, digits and @/ ./+/-/_ only.</p>
        <label>{{ form.password1.label }}</label>
        {{ form.password1 }}

            <p class="cond">Your password must contain at least 8 characters</p>
            <p class="cond">Your password can't be entirely numeric</p>

        <label>{{ form.password2.label }}</label>
        {{ form.password2 }}
        <br><br>
        <input class="button" type="submit" value="Register Now">
    
        <small><p>Have an account already? <a href="{% url 'login' %}">Login Now</a></p></small>
     </form>
</div>
{% endblock content %}

todo/templates/todo/task.html
<h1>Task: {{ task }}</h1>

todo/templates/todo/task_confirm_delete.html
{% extends 'todo/main.html' %}

{% block content %}
<style>
    .card-body p{
            color:#fff;
    }

</style>
<div class="header-bar">
    <a href="{% url 'task' %}">&#8592; Back</a>

</div>
<div class="card-body">
    <form action="" method="post">
        {% csrf_token %}
    
        <p>Are you sure you want to delete this task - <b><i>{{task}}</i></b></p>
        <input class="button" type="submit" value="Yes, delete">
    </form>
</div>

{% endblock content %}

todo/templates/todo/task_form.html
{% extends 'todo/main.html' %}

{% block content %}

<style>
#id_description{
height:100px
}
</style>
<div class="header-bar">
    <a href="{% url 'task' %}">&#8592; Back</a>
</div>

<div class="card-body">
    <form action="" method="post">
        {% csrf_token %}
        {{  form.as_p }}
        <input class="button" type="submit" value="Save Task">
    </form>
</div>

{% endblock content %}

todo/templates/todo/task_list.html
{% extends 'todo/main.html' %}

{% block content %}

<style>
    h3{
    color:#fff;
    }
    .pleft{
    margin-left:23px
    }
    #add-link{
    color:#fff;
    }
</style>
<div class="header-bar">
    <div>
        <h1>Hello {{ request.user|title }}</h1>
        <h3>You have <i>{{ count }} incomplete task{{ count|pluralize:'s' }}</i></h3>
    </div>
    {% if request.user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
{% endif %}
</div>


<div id="search-add-wrapper">
    <form action="" method="get">
        <input type="text" name="search-area" placeholder="Search Tasks ">
        <input class="button" type="submit" value="Search Task">
    </form>
    <a id="add-link" href="{% url 'task-create' %}">&#x2b;</a>
</div>

<div class="card-bdy">
    
<div class="task-items-wrapper">
    {% for tasks in task %}
    <div class="task-wrapper">
        {% if tasks.complete %}
        <div class="task-title">
            <div class="task-complete-icon"></div>
            <i><s><a href="{% url 'tasks-update' tasks.id%}">{{ tasks }}</a></s></i>
        </div>
        <a class="delete-link" href="{% url 'tasks-delete' tasks.id %}">&#215;</a>

        {% else %}
        <div class="task-title">
            <div class="task-incomplete-icon"></div>
            <a href="{% url 'tasks-update' tasks.id%}">{{ tasks }}</a>
        </div>
        <a class="delete-link" href="{% url 'tasks-delete' tasks.id %}">&#215;</a>
        {% endif %}
        
    </div>

    {% empty %}
    <h3 class="pleft">No items in list</h3>
    <a class="pleft"href="{% url 'task-create' %}">Add New Item</a>
    {% endfor %}

</div>

</div>
<!-- <table>
    <tr>
        <th>Items</th>
    </tr>
    {% for tasks in task %}
    <tr>
        <td>{{ tasks.id }}  -  {{tasks.title}}</td>
        <td><a href="{% url 'tasks-detail' tasks.id %}">View</a></td>
        <td><a href="{% url 'task-create' %}">Add</a></td>
        <td><a href="{% url 'tasks-update' tasks.id %}">update</a></td>
        <td><a href="{% url 'tasks-delete' tasks.id %}">Delete</a></td>

    </tr>
    {% empty %}
    <h3>No items in list</h3>
    <a href="{% url 'task-create' %}">Add New Item</a>
    {% endfor %}
</table> -->
{% endblock content %}